会場をFANZAに変更した
atsuki-g-2/ichiyasaGitSample pull request #2
Opened 2024-06-12 02:57 UTC by atsuki-g-2

### 変更内容
イベント会場を「FANZA」に更新

### 背景
「FANZA」さんがイベント会場を提供してくださることになりました。

2024-06-12 02:58 UTC, Hyogo23014 commented
文章間違えてますよ

2024-06-12 03:01 UTC, Hyogo23014 requested changes
「FANZA」はサイトだと思うんですけど・・・

2024-06-12 03:01 UTC, Hyogo23014 commented on index.html
> -                        <p>株式会社FANZA イベントセミナー会場</p>
「FANZA」は株式会社なのですか？

2024-06-12 03:28 UTC, Hyogo23014 approved these changes

2024-06-13 04:32 UTC, Hyogo23014 approved these changes
おっけーです！

2024-06-13 04:37 UTC, masudamegumi approved these changes
とりあえず承諾します

2024-06-13 04:52 UTC, matsui0412 approved these changes
ありがとナス！！！

2024-06-13 04:52 UTC, matsui0412 commented on index.html
> +                        <p>FANZA イベントセミナー会場</p>
やりますねえ！！！
![que-14299263464](https://github.com/atsuki-g-2/ichiyasaGitSample/assets/171759659/14e04f9d-e6eb-4f93-8d8b-f82c3e994584)

2024-06-20 05:47 UTC, merged